name: Cron Scheduler Test

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Show current time
        run: date
